apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-service
  namespace: default
  labels:
    app: deployment-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: deployment-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: deployment-service
    spec:
      containers:
        - name: deployment-service
          image: deployment-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4000
              name: http
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "4000"
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: deployment-service-secrets
                  key: mongodb-uri
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: deployment-service-secrets
                  key: redis-password
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: deployment-service-secrets
                  key: jwt-secret
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: deployment-service-secrets
                  key: aws-access-key-id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: deployment-service-secrets
                  key: aws-secret-access-key
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/app/credentials/google-credentials.json"
          volumeMounts:
            - name: google-credentials
              mountPath: "/app/credentials"
              readOnly: true
            - name: kubernetes-config
              mountPath: "/app/.kube"
              readOnly: true
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: google-credentials
          secret:
            secretName: google-credentials
        - name: kubernetes-config
          secret:
            secretName: kubernetes-config 