apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - deployment.yaml
  - service.yaml
  - secrets.yaml
  - dependencies.yaml

commonLabels:
  app.kubernetes.io/name: deployment-service
  app.kubernetes.io/part-of: novamind

configMapGenerator:
  - name: deployment-service-config
    literals:
      - LOG_LEVEL=info
      - LOG_FORMAT=json
      - RATE_LIMIT_POINTS=10
      - RATE_LIMIT_DURATION=1
      - RATE_LIMIT_BLOCK_DURATION=900

images:
  - name: deployment-service
    newName: deployment-service
    newTag: latest 