apiVersion: v1
kind: Secret
metadata:
  name: deployment-service-secrets
  namespace: default
type: Opaque
stringData:
  mongodb-uri: "mongodb://mongodb:27017/deployment-service"
  redis-password: ""  # Set your Redis password here
  jwt-secret: ""  # Set your JWT secret here
  aws-access-key-id: ""  # Set your AWS access key ID here
  aws-secret-access-key: ""  # Set your AWS secret access key here

---
apiVersion: v1
kind: Secret
metadata:
  name: google-credentials
  namespace: default
type: Opaque
stringData:
  google-credentials.json: |
    {
      # Add your Google Cloud service account credentials here
    }

---
apiVersion: v1
kind: Secret
metadata:
  name: kubernetes-config
  namespace: default
type: Opaque
stringData:
  config: |
    # Add your kubeconfig content here 