apiVersion: v1
kind: Service
metadata:
  name: deployment-service
  namespace: default
  labels:
    app: deployment-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: deployment-service 